### ISSUE TITLE
Xcode 6.3 version doesn't compile

### ISSUE THREAD

**Issue by randeepbhatia** [codestergit/SweetAlert-iOS#12]
Hi
I am trying to run the Xcode version 6.3 for the code but it doesn't compile. IT raises lot of issues related to init and type methods. 
I could resolve the type methods error but not init one. Can you help ?
-Randeep

**Comment by Max-Meng** [comment]
Same issue here, thanks.

**Comment by mokai** [comment]
Same issue here, thanks.

**Comment by mokai** [comment]
why not support swift1.2

**Comment by nagaho** [comment]
https://github.com/codestergit/SweetAlert-iOS/pull/9

**Comment by MakeHui** [comment]
I solved the issue and push requests to author https://github.com/MakeHui/SweetAlert-iOS

**Comment by yizhiheng** [comment]
@MakeHui Thank you so much! It helps a lot.

**Comment by codestergit** [comment]
Updated for Swift 2.0
