### ISSUE TITLE
Your SweetAlert is amazing!!!

### ISSUE THREAD

**Issue by DimonDeveloper** [codestergit/SweetAlert-iOS#3]
Your SweetAlert is amazing but you'll add to the possibility textfield and 3 or 4 buttons? It would be great.

**Comment by digitaldesaster** [comment]
Hi, just two suggestions from my side.

1.) there should be an option to autohide the alertview after x seconds.
2.) clicking on the black overlay should also dismiss the alert. 

thanks

**Comment by acegreen** [comment]
@digitaldesaster I just created a pull request for suggestion 1) see here: https://github.com/codestergit/SweetAlert-iOS/pull/22

**Comment by varkrishna** [comment]
@codestergit I just created a pull request for suggestion 2) see here: #62
