### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by justdan0227** [codestergit/SweetAlert-iOS#48]
Any chance on an update for Swift3?

**Comment by massigouel** [comment]
Try [https://github.com/codestergit/SweetAlert-iOS/pull/47/commits/57a153717b06c640d123a4192b197f5d5b0f6d83](url)
Make the necessary changes in your code. It should work. (worked for me: iOS 10 + swift 3)

**Comment by setoba1192** [comment]
@massigouel  the url is 404

**Comment by massigouel** [comment]
@setoba1192 Click on the Pull requested Tab / converted to swift 3 #47
