### ISSUE TITLE
Support to Modal Segues

### ISSUE THREAD

**Issue by RennanAlves** [codestergit/SweetAlert-iOS#8]
In the function showAlert isn't better to set the "window" (line 253) constant to "UIApplication.sharedApplication().keyWindow?.subviews.last"?

In my application, if I set the "keyWindow" to .first, the alert will be put in the back of a ViewController that is presented modally.

**Comment by junstor** [comment]
I was facing the same problem...

**Comment by alexperezpaya** [comment]
Same here :(

**Comment by x140yu** [comment]
same problem

**Comment by codestergit** [comment]
@RennanAlves  @junstor  @alexperezpaya  Can anyone please confirm. I have resolved the issue

**Comment by codestergit** [comment]
Please reopen if you get issue again. Closing for now.
